package com.example.debuggingdemonsapp.model;

import android.graphics.Bitmap;

import android.os.Parcel;
import android.os.Parcelable;
import androidx.annotation.NonNull;

import java.util.ArrayList;
import java.util.List;

/**
 * Photograph object which is has a bitmap and the uri of the image corresponding to
 *      its database uri
 */
public class Photograph implements Parcelable {
    private List<String> barcodeValues = new ArrayList<>();
    private String serialNumber;
    private Bitmap photo;
    private String uri = "";

    /**
     * This is the constructor for the Photograph class which takes in a Bitmap
     * @param savedPhoto Bitmap object which corresponds to the image being saved as a Photograph object
     */
    public Photograph(Bitmap savedPhoto){
        this.photo = savedPhoto;
    }

    /**
     * Method generated from the parcelable interface
     * @param in Parcel object
     */
    protected Photograph(Parcel in) {
        photo = in.readParcelable(Bitmap.class.getClassLoader());
        uri = in.readString();
    }

    /**
     * This method returns the photo's bitmap
     * @return Bitmap photo  The bitmap that is associated with a specific Photograph object
     */
    public Bitmap photoBitmap(){
        return this.photo;
    }

    /**
     * This method returns the photo's Uri
     * @return String uri  The uri as a string which is associated with a specific Photograph object
     */
    public String getUri(){
        return this.uri;
    }

    /**
     * This method sets the Barcode Value of this photograph based on what is passed to the function
     * @param barcodeValues The barcode values--as a list of strings--found from the image when it is scanned
     */
    public void setBarcodeValues(List<String> barcodeValues){
        this.barcodeValues = barcodeValues;
    }

    /**
     * This method returns the saved barcode values
     * @return barcodeValues the list of strings that contains all barcode values found in the image
     */
    public List<String> getBarcodeValues(){
        return this.barcodeValues;
    }


    /**
     * This method sets the Serial Number based on what is passed to the function
     * @param serialNumber The serial number--as a string--that is found from the scanned image
     */
    public void setSerialNumber(String serialNumber){
        this.serialNumber = serialNumber;
    }

    public String getSerialNumber(){
        return this.serialNumber;
    }
    /**
     * This method sets the Uri of the photo based on a database uri that is passed in
     * @param databaseURI A Firebase Storage Uri as a string which is passed into the method
     */
    public void setUri(String databaseURI){
        this.uri = databaseURI;
    }

    /**
     * Method is a part of the Parcelable interface
     * @return int
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * This method is used to allow Photograph objects to be passed between fragments in a bundle
     * @param parcel Parcel object from the interface
     * @param i Integer object from by the interface
     */
    @Override
    public void writeToParcel(@NonNull Parcel parcel, int i) {
        parcel.writeArray(new Object[] {this.uri, this.photo});
    }

    /**
     * Creator interface generated by the Parcelable interface
     */
    public static final Creator<Photograph> CREATOR = new Creator<Photograph>() {
        @Override
        public Photograph createFromParcel(Parcel in) {
            return new Photograph(in);
        }

        @Override
        public Photograph[] newArray(int size) {
            return new Photograph[size];
        }
    };
}